image: Visual Studio 2015

cache:
- "c:\\sr"

environment:
  global:
    STACK_ROOT: "c:\\sr"

matrix:
  - PATH_TO_PG_CONFIG: "C:\\Program Files (x86)\\PostgreSQL\\9.6\\bin"

build: off
test: off

branches:
  only:
    - windows-auto-release

install:
  - "SET PATH=%PATH_TO_PG_CONFIG%;%PATH%"

  - ECHO "Current PATH:"
  - cmd: ECHO %PATH%

  - ECHO "Debug: Do we have files in Postgres bin?"
  - ps: "ls $env:PATH_TO_PG_CONFIG"
  
  - ECHO "Debug: Running pg_config.exe"
  - cmd: pg_config

before_build:
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

build_script:
- stack setup --no-terminal > nul
- stack build --only-snapshot --no-terminal
- stack --local-bin-path . install postgrest

artifacts:
- path: postgrest.exe
