version: 2
jobs:
  build-test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-stack-dependencies-{{ checksum "postgrest.cabal" }}-{{ checksum "stack.yaml" }}
      - run:
          name: install stack & dependencies
          command: |
            curl -L https://github.com/commercialhaskell/stack/releases/download/v1.1.2/stack-1.1.2-linux-x86_64.tar.gz | tar zx -C /tmp
            sudo mv /tmp/stack-1.1.2-linux-x86_64/stack /usr/bin
            sudo apt-get update
            sudo apt-get install libgmp-dev
            sudo apt-get install --only-upgrade binutils
            stack setup
            rm -rf $(stack path --dist-dir) $(stack path --local-install-root)
            stack install hlint packdeps cabal-install
      - run:
          name: build src and tests
          command: |
            stack build --fast -j1
            stack build --fast --test --no-run-tests
      - run:
          name: run tests
          command: |
            sudo service postgresql start
            POSTGREST_TEST_CONNECTION=$(test/create_test_db "postgres://circleci@localhost" postgrest_test) stack test
            test/io-tests.sh
      - run:
          name: run linter
          command: git ls-files | grep '\.l\?hs$' | xargs stack exec -- hlint -X QuasiQuotes -X NoPatternSynonyms "$@"
      - run:
          name: extra build checks
          command: |
            stack exec -- cabal update
            stack exec --no-ghc-package-path -- cabal install --only-d --dry-run
            stack exec -- packdeps *.cabal || true
            stack exec -- cabal check
            stack haddock --no-haddock-deps
            stack sdist
      - save_cache:
          paths:
            - "~/.stack"
            - ".stack-work"
          key: v1-stack-dependencies-{{ checksum "postgrest.cabal" }}-{{ checksum "stack.yaml" }}

  build-centos6-bin:
    steps:
      - run:
          name: build binary
          command: |
            mkdir -p /tmp/bin/centos6
            echo "postgrest binary" > /tmp/bin/centos6/postgrest
      - persist_to_workspace:
          root: /tmp/bin/centos6
          paths:
            - postgrest

  build-centos7-bin:
    steps:
      - run:
          name: build binary
          command: |
            mkdir -p /tmp/bin/centos7
            echo "postgrest binary" > /tmp/bin/centos7/postgrest
      - persist_to_workspace:
          root: /tmp/bin/centos7
          paths:
            - postgrest

  release:
    steps:
      - attach_workspace:
          at: /tmp/bin
      - run: tree /tmp/bin

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-test
      - build-centos6-bin
          requires:
            - build-test
      - build-centos7-bin
          requires:
            - build-test
      - release
          requires:
            - build-centos6-bin
            - build-centos7-bin
