version: 2
jobs:
  build-test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-stack-dependencies-{{ checksum "postgrest.cabal" }}-{{ checksum "stack.yaml" }}
      - run:
          name: install stack & dependencies
          command: |
            curl -L https://github.com/commercialhaskell/stack/releases/download/v1.1.2/stack-1.1.2-linux-x86_64.tar.gz | tar zx -C /tmp
            sudo mv /tmp/stack-1.1.2-linux-x86_64/stack /usr/bin
            sudo apt-get update
            sudo apt-get install libgmp-dev
            sudo apt-get install --only-upgrade binutils
            stack setup
            rm -rf $(stack path --dist-dir) $(stack path --local-install-root)
            stack install hlint packdeps cabal-install
      - run:
          name: build src and tests
          command: |
            stack build --fast -j1
            stack build --fast --test --no-run-tests
      - run:
          name: run tests
          command: |
            sudo service postgresql start
            POSTGREST_TEST_CONNECTION=$(test/create_test_db "postgres://circleci@localhost" postgrest_test) stack test
            test/io-tests.sh
      - run:
          name: run linter
          command: git ls-files | grep '\.l\?hs$' | xargs stack exec -- hlint -X QuasiQuotes -X NoPatternSynonyms "$@"
      - run:
          name: extra checks
          command: |
            stack exec -- cabal update
            stack exec --no-ghc-package-path -- cabal install --only-d --dry-run
            stack exec -- packdeps *.cabal || true
            stack exec -- cabal check
            stack haddock --no-haddock-deps
            stack sdist
      - save_cache:
          paths:
            - "~/.stack"
            - ".stack-work"
          key: v1-stack-dependencies-{{ checksum "postgrest.cabal" }}-{{ checksum "stack.yaml" }}

  build-centos6-bin:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-centos6-dependencies-{{ checksum "postgrest.cabal" }}-{{ checksum "stack.yaml" }}
          - v1-centos6-image-{{ checksum "docker/distro_release/Dockerfile.centos6" }}
      - run:
          name: build docker image
          command: |
            if [[ -e ~/centos6.tar ]]; then
              docker load -i ~/centos6.tar
            else
              docker build --rm=false -t centos6 -f docker/distro_release/Dockerfile.centos6 docker/distro_release/
              docker save centos6 > ~/centos6.tar
            fi
      - run:
          name: build binary
          command: |
            docker run -it \
              -v $HOME/.stack:/root/.stack \
              -v $(pwd):/source \
              -v /tmp/:/root/.local/bin/ \
              centos6 build --allow-different-user --install-ghc --copy-bins
      - run:
          name: compress binary
          command: cd /tmp && tar cjf postgrest-centos6.tar.xz postgrest

      - persist_to_workspace:
          root: /tmp
          paths:
            - postgrest-centos6.tar.xz
      - save_cache:
          paths:
            - "~/.stack"
            - ".stack-work"
          key: v1-centos6-dependencies-{{ checksum "postgrest.cabal" }}-{{ checksum "stack.yaml" }}
      - save_cache:
          paths:
            - "~/centos6.tar"
          key: v1-centos6-image-{{ checksum "docker/distro_release/Dockerfile.centos6" }}

  build-centos7-bin:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-centos7-dependencies-{{ checksum "postgrest.cabal" }}-{{ checksum "stack.yaml" }}
          - v1-centos7-image-{{ checksum "docker/distro_release/Dockerfile.centos7" }}
      - run:
          name: build docker image
          command: |
            if [[ -e ~/centos7.tar ]]; then
              docker load -i ~/centos7.tar
            else
              docker build --rm=false -t centos7 -f docker/distro_release/Dockerfile.centos7 docker/distro_release/
              docker save centos7 > ~/centos7.tar
            fi
      - run:
          name: build binary
          command: |
            docker run -it \
              -v $HOME/.stack:/root/.stack \
              -v $(pwd):/source \
              -v /tmp/:/root/.local/bin/ \
              centos7 build --allow-different-user --install-ghc --copy-bins
      - run:
          name: compress binary
          command: cd /tmp && tar cjf postgrest-centos7.tar.xz postgrest

      - persist_to_workspace:
          root: /tmp
          paths:
            - postgrest-centos7.tar.xz
      - save_cache:
          paths:
            - "~/.stack"
            - ".stack-work"
          key: v1-centos7-dependencies-{{ checksum "postgrest.cabal" }}-{{ checksum "stack.yaml" }}
      - save_cache:
          paths:
            - "~/centos7.tar"
          key: v1-centos7-image-{{ checksum "docker/distro_release/Dockerfile.centos7" }}

  release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: upload bins to github release
          command: |
            go get -u github.com/tcnksm/ghr
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace v0.4.3.0 /tmp

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-test
      - build-centos6-bin:
          requires:
            - build-test
      - build-centos7-bin:
          requires:
            - build-test
      - release:
          requires:
            - build-centos6-bin
            - build-centos7-bin
